version: '3.9'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.55
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - '16686:16686' # Web UI
      - '4317:4317' # OTLP gRPC
      - '4318:4318' # OTLP HTTP
