"""Initial migration

Revision ID: 0b320dc5805b
Revises:
Create Date: 2025-05-18 19:40:16.758963

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "0b320dc5805b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
