"""add composite index on transactions

Revision ID: 634f04d91d4a
Revises: e93717034d3b
Create Date: 2025-06-18 19:43:35.759327

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "634f04d91d4a"
down_revision: Union[str, None] = "add_paid_status"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_transactions_quote_status",
        "transactions",
        ["quote_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_quote_status", table_name="transactions")
    # ### end Alembic commands ###
