"""Initial migration

Revision ID: 6f2a078f4cc0
Revises:
Create Date: 2025-06-04 20:03:07.989974

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "6f2a078f4cc0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
