global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'agentcloud'
    static_configs:
      - targets: ['api:8000'] # Uses Docker service name
    metrics_path: '/metrics'
    scrape_interval: 5s
